name: sync fork

on:
  schedule:
    - cron: '0 */3 * * *'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "Nathan Perry"
          git config user.email "np@nathanperry.dev"

      - name: pull branch
        run: |
          git remote add upstream $(jq -r .upstream < .upstream )
          readonly branch=$(jq -r .branch < .upstream)
          git fetch upstream "$branch"
          git rebase -Xtheirs upstream/"$branch"

      - name: push branch
        run: |
          git push -f origin $(jq -r .branch < .upstream)
          git push -f origin upstream/$(jq -r .branch < .upstream):refs/heads/upstream

      - name: mirror tags
        run: |
          git fetch upstream --tags
          git push -f origin --tags
